title: "The Playlist Gallery Project"
description: "Curating playlists using restrictions as art."
theme: minima

minima:
  skin: auto
  custom_css:
    - assets/css/custom.css
authors:
  - Bly
  - Curator's Assistant

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown